name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        run: newman run api-tests/postman_collection.json
